### ISSUE TITLE
potential NPE in TodoItem.equals method

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/todo-app-java-on-azure#24]
https://github.com/Microsoft/todo-app-java-on-azure/blob/master/src/main/java/com/microsoft/azure/sample/model/TodoItem.java#L70

```
 final TodoItem itemA = new TodoItem();
 final TodoItem itemB = new TodoItem("B", "Item B", "Owner of Item B");
```
` itemA.equals(itemB)` throws NPE.

**Comment by yuwzho** [comment]
Thanks for reporting this, and yan will resolve this
